/**
 * Bonanza-inspired mock catalog for ZIORA storefront demos.
 * Fashion lines mirror Pakistani RTW / unstitched retail structure.
 */

export type MockCategory = {
  name: string;
  slug: string;
};

export type MockProductInput = {
  name: string;
  slug: string;
  description: string;
  price: number;
  discountPrice: number;
  categorySlug: string;
  productLine: string;
  sku: string;
  sizes: string[];
  colors: string[];
  fabric?: string;
  careInstructions?: string;
  imageSeed: string;
  stockQuantity: number;
  isNewArrival: boolean;
  isFeatured: boolean;
};

export const MOCK_CATEGORIES: MockCategory[] = [
  { name: "Ready to Wear", slug: "ready-to-wear" },
  { name: "Unstitched", slug: "unstitched" },
  { name: "Festive Edit", slug: "festive-edit" },
  { name: "Everyday Essentials", slug: "everyday-essentials" },
  { name: "Premium Abayas", slug: "premium-abayas" },
];

function img(seed: string, w = 900, h = 1200) {
  return {
    url: `https://picsum.photos/seed/${seed}/${w}/${h}`,
    publicId: `mock/${seed}`,
    alt: seed.replace(/-/g, " "),
  };
}

export const MOCK_PRODUCTS: MockProductInput[] = [
  {
    name: "Rose Jacquard 3 Piece",
    slug: "rose-jacquard-3-piece",
    description:
      "Structured jacquard three-piece with soft rose ground and modest silhouette. Ideal for daytime gatherings and Eid mornings.",
    price: 9990,
    discountPrice: 5994,
    categorySlug: "ready-to-wear",
    productLine: "RTW Luxury",
    sku: "ZR-RTW-RJ3-051",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Rose", "Ivory"],
    fabric: "Jacquard blend",
    careInstructions: "Dry clean only",
    imageSeed: "ziora-rose-jacquard",
    stockQuantity: 18,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Lilac Lawn 2 Piece",
    slug: "lilac-lawn-2-piece",
    description:
      "Breathable lawn two-piece in muted lilac with clean neckline and relaxed straight pants.",
    price: 6490,
    discountPrice: 3894,
    categorySlug: "ready-to-wear",
    productLine: "RTW Basic",
    sku: "ZR-RTW-LL2-020",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Lilac"],
    fabric: "Premium lawn",
    careInstructions: "Hand wash cold",
    imageSeed: "ziora-lilac-lawn",
    stockQuantity: 24,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Multi Lawn 3 Piece",
    slug: "multi-lawn-3-piece",
    description:
      "Printed lawn three-piece with coordinated dupatta. Light drape for everyday summer wear.",
    price: 9290,
    discountPrice: 5574,
    categorySlug: "ready-to-wear",
    productLine: "RTW Basic",
    sku: "ZR-RTW-ML3-7A1",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Multi"],
    fabric: "Lawn",
    careInstructions: "Gentle machine wash",
    imageSeed: "ziora-multi-lawn",
    stockQuantity: 14,
    isNewArrival: false,
    isFeatured: true,
  },
  {
    name: "Peach Jacquard Kurti",
    slug: "peach-jacquard-kurti",
    description:
      "Single-piece jacquard kurti with soft peach tone and tailored sleeve — a wardrobe staple.",
    price: 3980,
    discountPrice: 2786,
    categorySlug: "ready-to-wear",
    productLine: "RTW Basic",
    sku: "ZR-RTW-PJK-002",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Peach"],
    fabric: "Jacquard",
    careInstructions: "Dry clean preferred",
    imageSeed: "ziora-peach-kurti",
    stockQuantity: 32,
    isNewArrival: true,
    isFeatured: false,
  },
  {
    name: "White Cambric 2 Piece",
    slug: "white-cambric-2-piece",
    description:
      "Crisp white cambric set with subtle texture. Pair with statement jewellery for evenings.",
    price: 5490,
    discountPrice: 3294,
    categorySlug: "ready-to-wear",
    productLine: "RTW Basic",
    sku: "ZR-RTW-WC2-113",
    sizes: ["S", "M", "L"],
    colors: ["White"],
    fabric: "Cambric",
    careInstructions: "Wash separately",
    imageSeed: "ziora-white-cambric",
    stockQuantity: 11,
    isNewArrival: false,
    isFeatured: true,
  },
  {
    name: "Navy Blended Kurta",
    slug: "navy-blended-kurta",
    description:
      "Deep navy blended kurta with clean placket and modest length for daily office wear.",
    price: 4890,
    discountPrice: 2934,
    categorySlug: "ready-to-wear",
    productLine: "Ready To Wear",
    sku: "ZR-RTW-NBK-009",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy"],
    fabric: "Blended cotton",
    careInstructions: "Machine wash cold",
    imageSeed: "ziora-navy-kurta",
    stockQuantity: 20,
    isNewArrival: false,
    isFeatured: false,
  },
  {
    name: "Misl Unstitched 3 Pc",
    slug: "misl-unstitched-3pc",
    description:
      "Unstitched three-piece lawn with digital print panel and matching dupatta — cut to your tailor.",
    price: 8990,
    discountPrice: 5394,
    categorySlug: "unstitched",
    productLine: "Unstitched Basic",
    sku: "ZR-US-MIS-062",
    sizes: ["Free Size"],
    colors: ["Multi"],
    fabric: "Lawn",
    careInstructions: "Wash before stitching",
    imageSeed: "ziora-misl-us",
    stockQuantity: 40,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Lavender Royale 3 Pc",
    slug: "lavender-royale-3pc",
    description:
      "Soft lavender unstitched suite with embroidered neckline motif and chiffon dupatta.",
    price: 7990,
    discountPrice: 4794,
    categorySlug: "unstitched",
    productLine: "Unstitched Basic",
    sku: "ZR-US-LR-147",
    sizes: ["Free Size"],
    colors: ["Lavender"],
    fabric: "Lawn + chiffon",
    careInstructions: "Dry clean embroidery panels",
    imageSeed: "ziora-lavender-royale",
    stockQuantity: 28,
    isNewArrival: true,
    isFeatured: false,
  },
  {
    name: "Dandelion Dream 3 Pc",
    slug: "dandelion-dream-3pc",
    description:
      "Sunny dandelion print on airy lawn. Three-piece unstitched for spring gatherings.",
    price: 8990,
    discountPrice: 5394,
    categorySlug: "unstitched",
    productLine: "Unstitched Basic",
    sku: "ZR-US-DD-047",
    sizes: ["Free Size"],
    colors: ["Yellow Multi"],
    fabric: "Lawn",
    careInstructions: "Cold wash, shade dry",
    imageSeed: "ziora-dandelion",
    stockQuantity: 22,
    isNewArrival: false,
    isFeatured: true,
  },
  {
    name: "Zarposh Barkha 3 Pc",
    slug: "zarposh-barkha-3pc",
    description:
      "Monsoon-inspired barkha print with contrast borders. Unstitched three-piece set.",
    price: 8990,
    discountPrice: 5394,
    categorySlug: "unstitched",
    productLine: "Unstitched Basic",
    sku: "ZR-US-ZB-047",
    sizes: ["Free Size"],
    colors: ["Teal Multi"],
    fabric: "Lawn",
    careInstructions: "Hand wash recommended",
    imageSeed: "ziora-zarposh",
    stockQuantity: 16,
    isNewArrival: false,
    isFeatured: false,
  },
  {
    name: "L-Blue Jacquard Unstitched",
    slug: "l-blue-jacquard-unstitched",
    description:
      "Luxury light-blue jacquard unstitched three-piece with woven sheen for formal wear.",
    price: 5990,
    discountPrice: 3594,
    categorySlug: "unstitched",
    productLine: "Unstitched Luxury",
    sku: "ZR-US-LBJ-049",
    sizes: ["Free Size"],
    colors: ["Light Blue"],
    fabric: "Jacquard",
    careInstructions: "Dry clean only",
    imageSeed: "ziora-lblue-jacq",
    stockQuantity: 12,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Lime Zest 3 Pc",
    slug: "lime-zest-3pc",
    description:
      "Fresh lime print unstitched set — lightweight and bright for summer chaand raat looks.",
    price: 5290,
    discountPrice: 3703,
    categorySlug: "unstitched",
    productLine: "Unstitched Basic",
    sku: "ZR-US-LZ-4M7",
    sizes: ["Free Size"],
    colors: ["Lime"],
    fabric: "Lawn",
    careInstructions: "Gentle wash",
    imageSeed: "ziora-lime-zest",
    stockQuantity: 35,
    isNewArrival: true,
    isFeatured: false,
  },
  {
    name: "Rust Jacquard 3 Piece",
    slug: "rust-jacquard-3-piece",
    description:
      "Warm rust jacquard unstitched three-piece with tonal self-design for winter evenings.",
    price: 6490,
    discountPrice: 4543,
    categorySlug: "unstitched",
    productLine: "Unstitched Basic",
    sku: "ZR-US-RJ-1F8",
    sizes: ["Free Size"],
    colors: ["Rust"],
    fabric: "Jacquard",
    careInstructions: "Dry clean",
    imageSeed: "ziora-rust-jacq",
    stockQuantity: 19,
    isNewArrival: false,
    isFeatured: true,
  },
  {
    name: "Nomadic 2 Pc",
    slug: "nomadic-2pc",
    description:
      "Compact two-piece unstitched print for quick tailor turns — understated and wearable.",
    price: 2790,
    discountPrice: 1953,
    categorySlug: "unstitched",
    productLine: "Unstitched Basic",
    sku: "ZR-US-NOM-512",
    sizes: ["Free Size"],
    colors: ["Sand"],
    fabric: "Cambric",
    careInstructions: "Machine wash",
    imageSeed: "ziora-nomadic",
    stockQuantity: 48,
    isNewArrival: true,
    isFeatured: false,
  },
  {
    name: "Zoey Festive 3 Pc",
    slug: "zoey-festive-3pc",
    description:
      "Festive unstitched luxury set with sequin accents on the neckline panel and organza dupatta.",
    price: 7990,
    discountPrice: 5593,
    categorySlug: "festive-edit",
    productLine: "Unstitched Luxury",
    sku: "ZR-FE-ZOEY-124",
    sizes: ["Free Size"],
    colors: ["Ivory Gold"],
    fabric: "Organza blend",
    careInstructions: "Dry clean only — handle sequins carefully",
    imageSeed: "ziora-zoey-festive",
    stockQuantity: 9,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Nora Festive 3 Pc",
    slug: "nora-festive-3pc",
    description:
      "Deep emerald festive suite with zari borders. Designed for mehndi and dinner nights.",
    price: 7390,
    discountPrice: 4434,
    categorySlug: "festive-edit",
    productLine: "Unstitched Luxury",
    sku: "ZR-FE-NORA-088",
    sizes: ["Free Size"],
    colors: ["Emerald"],
    fabric: "Net + silk blend",
    careInstructions: "Dry clean only",
    imageSeed: "ziora-nora-festive",
    stockQuantity: 7,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Zariyah Festive 3 Pc",
    slug: "zariyah-festive-3pc",
    description:
      "Rich maroon festive three-piece with heavy embroidery and soft tissue dupatta.",
    price: 8990,
    discountPrice: 6293,
    categorySlug: "festive-edit",
    productLine: "Unstitched Luxury",
    sku: "ZR-FE-ZAR-9O7",
    sizes: ["Free Size"],
    colors: ["Maroon"],
    fabric: "Embroidered lawn + tissue",
    careInstructions: "Dry clean",
    imageSeed: "ziora-zariyah",
    stockQuantity: 6,
    isNewArrival: false,
    isFeatured: true,
  },
  {
    name: "Pure Elegance 3 Pc",
    slug: "pure-elegance-3pc",
    description:
      "Ivory-on-ivory festive embroidery with pearl detail. A classic for formal receptions.",
    price: 9990,
    discountPrice: 6993,
    categorySlug: "festive-edit",
    productLine: "Unstitched Luxury",
    sku: "ZR-FE-PE-10N5",
    sizes: ["Free Size"],
    colors: ["Ivory"],
    fabric: "Organza",
    careInstructions: "Professional dry clean",
    imageSeed: "ziora-pure-elegance",
    stockQuantity: 5,
    isNewArrival: true,
    isFeatured: false,
  },
  {
    name: "Aura Everyday Kurta",
    slug: "aura-everyday-kurta",
    description:
      "Soft everyday kurta in muted sage with side slits and breathable cotton feel.",
    price: 4990,
    discountPrice: 3493,
    categorySlug: "everyday-essentials",
    productLine: "Everyday",
    sku: "ZR-EE-AURA-2M5",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sage", "Stone"],
    fabric: "Cotton blend",
    careInstructions: "Machine wash cold",
    imageSeed: "ziora-aura-kurta",
    stockQuantity: 30,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Skyline 2 Pc Essential",
    slug: "skyline-2pc-essential",
    description:
      "Minimal sky-blue two-piece for daily wear — clean lines, zero fuss.",
    price: 2790,
    discountPrice: 1953,
    categorySlug: "everyday-essentials",
    productLine: "Everyday",
    sku: "ZR-EE-SKY-4M6",
    sizes: ["S", "M", "L"],
    colors: ["Sky"],
    fabric: "Lawn",
    careInstructions: "Easy wash",
    imageSeed: "ziora-skyline",
    stockQuantity: 42,
    isNewArrival: true,
    isFeatured: false,
  },
  {
    name: "Basis Printed 3 Pc",
    slug: "basis-printed-3pc",
    description:
      "Everyday printed three-piece with soft pastel ground — office to weekend.",
    price: 5290,
    discountPrice: 3703,
    categorySlug: "everyday-essentials",
    productLine: "Everyday",
    sku: "ZR-EE-BAS-4M5",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pastel Multi"],
    fabric: "Lawn",
    careInstructions: "Gentle cycle",
    imageSeed: "ziora-basis",
    stockQuantity: 26,
    isNewArrival: false,
    isFeatured: true,
  },
  {
    name: "Gul Bahar Essential",
    slug: "gul-bahar-essential",
    description:
      "Floral gul bahar print on soft cotton. Coordinated bottoms included.",
    price: 9990,
    discountPrice: 6993,
    categorySlug: "everyday-essentials",
    productLine: "Everyday",
    sku: "ZR-EE-GB-1F5",
    sizes: ["S", "M", "L"],
    colors: ["Floral"],
    fabric: "Cotton",
    careInstructions: "Wash inside out",
    imageSeed: "ziora-gulbahar",
    stockQuantity: 15,
    isNewArrival: false,
    isFeatured: false,
  },
  {
    name: "Noir Flow Abaya",
    slug: "noir-flow-abaya",
    description:
      "Fluid black abaya with soft shoulder drape and concealed front placket. Travel-ready modest essential.",
    price: 8490,
    discountPrice: 0,
    categorySlug: "premium-abayas",
    productLine: "Premium Abayas",
    sku: "ZR-AB-NOIR-001",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    fabric: "Nida",
    careInstructions: "Steam only — do not iron hot",
    imageSeed: "ziora-noir-abaya",
    stockQuantity: 21,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Sand Whisper Abaya",
    slug: "sand-whisper-abaya",
    description:
      "Warm sand abaya with subtle cuff detail and breathable nida for all-day wear.",
    price: 7890,
    discountPrice: 6312,
    categorySlug: "premium-abayas",
    productLine: "Premium Abayas",
    sku: "ZR-AB-SAND-014",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sand"],
    fabric: "Premium nida",
    careInstructions: "Dry clean or gentle steam",
    imageSeed: "ziora-sand-abaya",
    stockQuantity: 13,
    isNewArrival: true,
    isFeatured: true,
  },
  {
    name: "Olive Umbrella Abaya",
    slug: "olive-umbrella-abaya",
    description:
      "Umbrella-cut olive abaya with soft volume and modest wrist finish.",
    price: 7290,
    discountPrice: 0,
    categorySlug: "premium-abayas",
    productLine: "Premium Abayas",
    sku: "ZR-AB-OLV-022",
    sizes: ["M", "L", "XL"],
    colors: ["Olive"],
    fabric: "Nida",
    careInstructions: "Hang to store",
    imageSeed: "ziora-olive-abaya",
    stockQuantity: 8,
    isNewArrival: false,
    isFeatured: false,
  },
  {
    name: "Ivory Crescent Abaya",
    slug: "ivory-crescent-abaya",
    description:
      "Ivory abaya with crescent embroidery at the cuff — quiet luxury for prayer and travel.",
    price: 9190,
    discountPrice: 7352,
    categorySlug: "premium-abayas",
    productLine: "Premium Abayas",
    sku: "ZR-AB-IVC-031",
    sizes: ["S", "M", "L"],
    colors: ["Ivory"],
    fabric: "Crepe nida",
    careInstructions: "Dry clean embroidery",
    imageSeed: "ziora-ivory-abaya",
    stockQuantity: 4,
    isNewArrival: true,
    isFeatured: true,
  },
];

export function buildProductImages(imageSeed: string, name: string) {
  const thumbnail = { ...img(imageSeed), alt: name };
  const images = [
    { ...img(`${imageSeed}-a`, 900, 1200), alt: `${name} detail` },
    { ...img(`${imageSeed}-b`, 900, 1200), alt: `${name} back` },
    { ...img(`${imageSeed}-c`, 900, 1200), alt: `${name} fabric` },
  ];
  return { thumbnail, images };
}
